-- Switch to the Pluggable Database
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Grant privileges to PDBADMIN
GRANT CREATE TABLE TO PDBADMIN;
GRANT UNLIMITED TABLESPACE TO PDBADMIN;
GRANT DBA TO PDBADMIN;

EXIT;